
server:
  port: 9091
  
spring:
  application:
    name: CUSTOMER_SERVICE_1
    
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    
  h2:
    console:
      enabled: true
    
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    
eureka:
  client:
    register-with-eureka: true 
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
     hostname: localhost  

